spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

fetcher:
  schedule:
    courses: ${SCHEDULE_COURSES:0 0 3 1 8 *}
    bandi: ${SCHEDULE_BANDI:0 0 4 * * *}
    dottorati: ${SCHEDULE_DOTTORATI:0 0 5 * * *}
    inpa: ${SCHEDULE_INPA:0 0 6 * * *}
    epso: ${SCHEDULE_EPSO:0 0 2 * * 0}
    ordini: ${SCHEDULE_ORDINI:0 0 1 1 * *}
  api:
    inpa-key: ${INPA_API_KEY}
    epso-key: ${EPSO_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    root: WARN
    org.ohmyopensource: INFO